#define CHILD_ID_TEMP 0
#define CHILD_ID_HEAT_STATE 3
#define CHILD_ID_SET_POINT 4
#define CHILD_ID_ENERGY 5     // 4 sensors here
#define CHILD_ID_START 10
#define MQ_SENSOR_CHILD_ID 13
#define LIGHT_CHILD_ID 14
#define BARO_CHILD_ID 15
#define TEMP_CHILD_ID  16
#define FORECAST_CHILD_ID 17
#define RELAY_CHILD_ID 18
#define BOILER_STATUS_ID 19
#define BOILER_GAS_ID 20
#define BOILER_CIRCU_ID 21
#define CHILD_ID_THERMAL_TANK_STATE 22
#define CHILD_ELECTRICAL_TANK_STATE 23
#define CHILD_ID_SET_POINT_TANK 24
#define CHILD_ID_HW_TEMP 25 //2 temp
#define CHILD_ID_3WV 27
